eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
#server:
#  port: 8761
